In [7]:
import numpy as np
import pandas as pd
from datetime import datetime 
from datetime import timedelta
import csv 
import matplotlib.pyplot as plt
from datetime import date
from datetime import time
import calendar
import locale
import seaborn as sns

In [8]:
def convertTimeStamp(string):
    """Converts a string to a datetime object.
    """
    time = datetime.strptime(string,'%m/%d/%Y %I:%M:%S %p') #Accepts time string, converts it to datetime object.
    return time

In [9]:
#convert seconds to weeks, days, hours, minutes, seconds

intervals = (
    ('weeks', 604800),  # 60 * 60 * 24 * 7
    ('days', 86400),    # 60 * 60 * 24
    ('hours', 3600),    # 60 * 60
    ('minutes', 60),
    ('seconds', 1),
    )

def display_time(seconds, granularity=2):
    result = []

    for name, count in intervals:
        value = seconds // count
        if value:
            seconds -= value * count
            if value == 1:
                name = name.rstrip('s')
            result.append("{} {}".format(value, name))
    return ', '.join(result[:granularity])

In [10]:
def elapsedInMonths(filepath):
    """councilTime accepts a csv file and returns a dataframe which displays the average elapsed time between created date 
        and update date for service requests in each distinct council district.
        
        Data source: https://data.lacity.org/A-Well-Run-City/MyLA311-Service-Request-Data-2017/d4vt-q4t5
        """
    
    dataframe = pd.read_csv(filepath)
    
    
    #filter dateset to CreatedDate and UpdatedDate columns
    created_df = dataframe['CreatedDate'].dropna().apply(convertTimeStamp, 0) #apply convertTimeStamp to CreatedDate
    updated_df = dataframe['UpdatedDate'].dropna().apply(convertTimeStamp, 0) #apply convertTimeStamp to UpdatedDate
    
    
    #create elapsed time and elapsed seconds columns and insert into dataframe
    elapsed_df = updated_df - created_df #calculate the difference in the values in CreatedDate and UpdatedDate
    dataframe.insert(3, "ElapsedTime", elapsed_df) #insert column ElapsedTime with dataframe elapsed_df into dataframe dataframe
    elapsed_seconds = dataframe['ElapsedTime'].dt.total_seconds() #convert ElapsedTime values to seconds
    dataframe.insert(4, 'ElapsedTime in Seconds', elapsed_seconds)
    
    
    #convert CreatedDate and UpdatedDate to datetime objects
    created_df = pd.to_datetime(dataframe['CreatedDate'], format='%m/%d/%Y %I:%M:%S %p')
    updated_df = pd.to_datetime(dataframe['UpdatedDate'], format='%m/%d/%Y %I:%M:%S %p')
    
    
    df4 = dataframe[['CreatedDate', 'UpdatedDate', 'ElapsedTime', 'ElapsedTime in Seconds']] #create a dataframe df4 with dates and elapsed time columns from dataframe
    df4 = df4.sort_values(by = 'CreatedDate')
        
    
    #create a dataframe of the months of CreatedDate rows
    for row in range(0, len(created_df)-1):
        created_df[row] = created_df[row].month
        
    
    #create dataframes for each unique month with ElapsedTime column
    monthsList = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
    for num in range(0,11):
        month = monthsList[num]
        print('Elapsed Times in', month)
        
        #group CreatedDate by month
        is_month =  created_df==num+1
        df4_month = df4[is_month]
        
        #print columns CreatedDate, UpdatedDate, ElapsedTime, ElapsedTime in Seconds
        month_time = df4_month[['CreatedDate', 'UpdatedDate', 'ElapsedTime']]
        print(month_time)

        #find average elapsed time for each month
        elapsed_avg = df4_month['ElapsedTime in Seconds'].mean()
        elapsed_avg = display_time(elapsed_avg, 5)

        print('\nAverage Elapsed Time in', monthsList[num],':', elapsed_avg)
        print('\n\n')

In [11]:
elapsedInMonths(r"C:\Users\hanaa\Downloads\MyLA311_Service_Request_Data_2017.csv")

C:\Users\hanaa\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3249: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

Elapsed Times in January

C:\Users\hanaa\Anaconda3\lib\site-packages\ipykernel_launcher.py:42: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

                    CreatedDate             UpdatedDate      ElapsedTime
1131554  01/01/2017 01:01:00 AM  01/04/2017 05:33:00 PM  3 days 16:32:00
1131330  01/01/2017 01:01:00 PM  01/03/2017 08:54:00 AM  1 days 19:53:00
1131328  01/01/2017 01:01:00 PM  01/03/2017 08:52:00 AM  1 days 19:51:00
1131329  01/01/2017 01:01:00 PM  01/09/2017 01:19:00 PM  8 days 00:18:00
1131327  01/01/2017 01:02:00 PM  01/17/2017 12:29:00 PM 15 days 23:27:00
...                         ...                     ...              ...
1047066  01/31/2017 12:58:00 PM  02/01/2017 12:04:00 PM  0 days 23:06:00
1047058  01/31/2017 12:59:00 PM  02/06/2017 12:13:00 PM  5 days 23:14:00
1047057  01/31/2017 12:59:00 PM  02/01/2017 01:18:00 PM  1 days 00:19:00
1047060  01/31/2017 12:59:00 PM  04/13/2017 09:34:00 AM 71 days 20:35:00
1047059  01/31/2017 12:59:00 PM  02/02/2017 05:04:00 PM  2 days 04:05:00

[86566 rows x 3 columns]

Average Elapsed Time in January : 4.0 days, 23.0 hours, 2.0 minutes, 7.0 seconds



Elapsed Times in February
                    CreatedDate             UpdatedDate     ElapsedTime
1042675  02/01/2017 01:00:00 PM  02/11/2017 07:38:00 AM 9 days 18:38:00
1042674  02/01/2017 01:00:00 PM  02/01/2017 01:03:00 PM 0 days 00:03:00
1042662  02/01/2017 01:01:00 PM  02/03/2017 11:35:00 AM 1 days 22:34:00
1042663  02/01/2017 01:01:00 PM  02/01/2017 01:01:00 PM 0 days 00:00:00
1042664  02/01/2017 01:01:00 PM  02/01/2017 01:01:00 PM 0 days 00:00:00
...                         ...                     ...             ...
969149   02/28/2017 12:58:00 PM  03/03/2017 12:08:00 PM 2 days 23:10:00
969144   02/28/2017 12:59:00 PM  03/03/2017 05:19:00 PM 3 days 04:20:00
969145   02/28/2017 12:59:00 PM  03/03/2017 04:35:00 PM 3 days 03:36:00
969146   02/28/2017 12:59:00 PM  03/02/2017 11:35:00 AM 1 days 22:36:00
969143   02/28/2017 12:59:00 PM  03/03/2017 01:45:00 PM 3 days 00:46:00

[77830 rows x 3 columns]

Average Elapsed Time in February : 5.0 days, 3.0 hours, 17.0 minutes, 21.0 seconds



Elapsed Times in March
                   CreatedDate             UpdatedDate       ElapsedTime
964527  03/01/2017 01:00:00 PM  03/01/2017 02:39:00 PM   0 days 01:39:00
964528  03/01/2017 01:00:00 PM  03/08/2017 01:41:00 PM   7 days 00:41:00
964529  03/01/2017 01:00:00 PM  03/09/2017 07:22:00 AM   7 days 18:22:00
964530  03/01/2017 01:00:00 PM  03/01/2017 01:00:00 PM   0 days 00:00:00
964531  03/01/2017 01:00:00 PM  03/01/2017 01:00:00 PM   0 days 00:00:00
...                        ...                     ...               ...
869395  03/31/2017 12:58:00 PM  04/05/2017 03:54:00 PM   5 days 02:56:00
869394  03/31/2017 12:58:00 PM  04/04/2017 09:50:00 AM   3 days 20:52:00
869397  03/31/2017 12:58:00 PM  01/17/2018 01:06:00 PM 292 days 00:08:00
869396  03/31/2017 12:58:00 PM  03/31/2017 01:01:00 PM   0 days 00:03:00
869393  03/31/2017 12:59:00 PM  04/07/2017 09:44:00 AM   6 days 20:45:00

[98867 rows x 3 columns]

Average Elapsed Time in March : 5.0 days, 4.0 hours, 34.0 minutes, 37.0 seconds



Elapsed Times in April
                   CreatedDate             UpdatedDate     ElapsedTime
867551  04/01/2017 01:00:00 PM  04/04/2017 07:14:00 PM 3 days 06:14:00
867550  04/01/2017 01:00:00 PM  04/03/2017 07:39:00 AM 1 days 18:39:00
867549  04/01/2017 01:01:00 PM  04/01/2017 01:02:00 PM 0 days 00:01:00
867548  04/01/2017 01:02:00 PM  04/02/2017 09:20:00 AM 0 days 20:18:00
867547  04/01/2017 01:02:00 PM  04/04/2017 07:44:00 AM 2 days 18:42:00
...                        ...                     ...             ...
782033  04/30/2017 12:56:00 PM  05/02/2017 03:31:00 PM 2 days 02:35:00
782032  04/30/2017 12:56:00 PM  05/02/2017 11:39:00 AM 1 days 22:43:00
782031  04/30/2017 12:57:00 PM  05/02/2017 11:36:00 AM 1 days 22:39:00
782030  04/30/2017 12:58:00 PM  05/02/2017 02:01:00 PM 2 days 01:03:00
782029  04/30/2017 12:59:00 PM  05/03/2017 11:46:00 AM 2 days 22:47:00

[87051 rows x 3 columns]

Average Elapsed Time in April : 5.0 days, 1.0 hour, 22.0 minutes, 47.0 seconds



Elapsed Times in May
                   CreatedDate             UpdatedDate     ElapsedTime
779215  05/01/2017 01:00:00 PM  05/04/2017 05:39:00 AM 2 days 16:39:00
779214  05/01/2017 01:00:00 PM  05/09/2017 04:52:00 PM 8 days 03:52:00
779213  05/01/2017 01:00:00 PM  05/04/2017 03:08:00 PM 3 days 02:08:00
779212  05/01/2017 01:00:00 PM  05/02/2017 04:24:00 PM 1 days 03:24:00
779211  05/01/2017 01:00:00 PM  05/04/2017 04:33:00 PM 3 days 03:33:00
...                        ...                     ...             ...
687143  05/31/2017 12:58:00 PM  06/01/2017 03:04:00 PM 1 days 02:06:00
687140  05/31/2017 12:58:00 PM  06/09/2017 02:59:00 PM 9 days 02:01:00
687136  05/31/2017 12:59:00 PM  06/09/2017 02:56:00 PM 9 days 01:57:00
687135  05/31/2017 12:59:00 PM  06/01/2017 03:12:00 PM 1 days 02:13:00
687134  05/31/2017 12:59:00 PM  06/01/2017 05:44:00 PM 1 days 04:45:00

[96447 rows x 3 columns]

Average Elapsed Time in May : 5.0 days, 5.0 hours, 3.0 minutes, 43.0 seconds



Elapsed Times in June
                   CreatedDate             UpdatedDate       ElapsedTime
684780  06/01/2017 01:00:00 AM  08/10/2017 07:42:00 AM  70 days 06:42:00
682346  06/01/2017 01:00:00 PM  06/08/2017 07:10:00 PM   7 days 06:10:00
682348  06/01/2017 01:00:00 PM  06/02/2017 03:37:00 PM   1 days 02:37:00
682347  06/01/2017 01:00:00 PM  06/07/2017 03:57:00 AM   5 days 14:57:00
682345  06/01/2017 01:01:00 PM  06/02/2017 07:41:00 AM   0 days 18:40:00
...                        ...                     ...               ...
587780  06/30/2017 12:59:00 PM  04/18/2018 02:10:00 PM 292 days 01:11:00
587779  06/30/2017 12:59:00 PM  07/08/2017 01:46:00 PM   8 days 00:47:00
587778  06/30/2017 12:59:00 PM  07/02/2017 01:35:00 PM   2 days 00:36:00
587777  06/30/2017 12:59:00 PM  07/03/2017 09:51:00 AM   2 days 20:52:00
587776  06/30/2017 12:59:00 PM  07/05/2017 12:49:00 PM   4 days 23:50:00

[98490 rows x 3 columns]

Average Elapsed Time in June : 5.0 days, 7.0 hours, 10.0 minutes, 46.0 seconds



Elapsed Times in July
                   CreatedDate             UpdatedDate     ElapsedTime
585396  07/01/2017 01:00:00 PM  07/06/2017 09:27:00 AM 4 days 20:27:00
585395  07/01/2017 01:00:00 PM  07/05/2017 03:24:00 PM 4 days 02:24:00
585393  07/01/2017 01:00:00 PM  07/03/2017 10:43:00 AM 1 days 21:43:00
585392  07/01/2017 01:00:00 PM  07/03/2017 10:32:00 AM 1 days 21:32:00
585394  07/01/2017 01:00:00 PM  07/03/2017 10:33:00 AM 1 days 21:33:00
...                        ...                     ...             ...
485620  07/31/2017 12:59:00 PM  07/31/2017 12:59:00 PM 0 days 00:00:00
485619  07/31/2017 12:59:00 PM  08/01/2017 01:15:00 PM 1 days 00:16:00
485618  07/31/2017 12:59:00 PM  08/03/2017 09:05:00 AM 2 days 20:06:00
485617  07/31/2017 12:59:00 PM  08/07/2017 07:22:00 PM 7 days 06:23:00
485615  07/31/2017 12:59:00 PM  08/01/2017 11:48:00 AM 0 days 22:49:00

[103541 rows x 3 columns]

Average Elapsed Time in July : 5.0 days, 14.0 hours, 34.0 minutes, 9.0 seconds



Elapsed Times in August
                   CreatedDate             UpdatedDate      ElapsedTime
479465  08/01/2017 01:00:00 PM  08/04/2017 01:46:00 PM  3 days 00:46:00
479462  08/01/2017 01:00:00 PM  08/02/2017 02:46:00 PM  1 days 01:46:00
479463  08/01/2017 01:00:00 PM  08/03/2017 04:02:00 PM  2 days 03:02:00
479464  08/01/2017 01:00:00 PM  08/04/2017 02:04:00 PM  3 days 01:04:00
479467  08/01/2017 01:00:00 PM  08/14/2017 03:02:00 PM 13 days 02:02:00
...                        ...                     ...              ...
370498  08/31/2017 12:58:00 PM  09/05/2017 03:24:00 PM  5 days 02:26:00
370497  08/31/2017 12:58:00 PM  09/06/2017 12:41:00 PM  5 days 23:43:00
370496  08/31/2017 12:59:00 PM  09/01/2017 07:30:00 AM  0 days 18:31:00
370495  08/31/2017 12:59:00 PM  09/01/2017 05:01:00 PM  1 days 04:02:00
370494  08/31/2017 12:59:00 PM  09/01/2017 09:39:00 AM  0 days 20:40:00

[113811 rows x 3 columns]

Average Elapsed Time in August : 4.0 days, 23.0 hours, 6.0 minutes, 55.0 seconds



Elapsed Times in September
                   CreatedDate             UpdatedDate      ElapsedTime
367256  09/01/2017 01:00:00 PM  09/12/2017 06:20:00 AM 10 days 17:20:00
367255  09/01/2017 01:00:00 PM  09/06/2017 09:43:00 AM  4 days 20:43:00
367258  09/01/2017 01:00:00 PM  09/01/2017 01:03:00 PM  0 days 00:03:00
367257  09/01/2017 01:00:00 PM  09/07/2017 08:23:00 AM  5 days 19:23:00
368879  09/01/2017 01:01:00 AM  09/05/2017 08:44:00 AM  4 days 07:43:00
...                        ...                     ...              ...
268951  09/30/2017 12:57:00 PM  10/03/2017 06:41:00 AM  2 days 17:44:00
268950  09/30/2017 12:58:00 PM  10/05/2017 03:27:00 PM  5 days 02:29:00
268947  09/30/2017 12:59:00 PM  10/02/2017 10:16:00 PM  2 days 09:17:00
268948  09/30/2017 12:59:00 PM  10/05/2017 12:49:00 PM  4 days 23:50:00
268949  09/30/2017 12:59:00 PM  10/10/2017 04:09:00 PM 10 days 03:10:00

[100712 rows x 3 columns]

Average Elapsed Time in September : 5.0 days, 2.0 hours, 35.0 minutes, 21.0 seconds



Elapsed Times in October
                   CreatedDate             UpdatedDate     ElapsedTime
268232  10/01/2017 01:00:00 AM  10/04/2017 02:25:00 PM 3 days 13:25:00
267770  10/01/2017 01:00:00 PM  10/03/2017 02:22:00 PM 2 days 01:22:00
267768  10/01/2017 01:00:00 PM  10/03/2017 03:47:00 PM 2 days 02:47:00
267769  10/01/2017 01:00:00 PM  10/02/2017 08:25:00 PM 1 days 07:25:00
267767  10/01/2017 01:01:00 PM  10/03/2017 02:20:00 PM 2 days 01:19:00
...                        ...                     ...             ...
173264  10/31/2017 12:59:00 PM  11/01/2017 09:39:00 AM 0 days 20:40:00
173265  10/31/2017 12:59:00 PM  11/03/2017 12:52:00 PM 2 days 23:53:00
173266  10/31/2017 12:59:00 PM  11/02/2017 09:41:00 AM 1 days 20:42:00
173267  10/31/2017 12:59:00 PM  11/01/2017 06:58:00 PM 1 days 05:59:00
173268  10/31/2017 12:59:00 PM  10/31/2017 02:20:00 PM 0 days 01:21:00

[96921 rows x 3 columns]

Average Elapsed Time in October : 4.0 days, 17.0 hours, 52.0 minutes, 56.0 seconds



Elapsed Times in November
                   CreatedDate             UpdatedDate      ElapsedTime
169401  11/01/2017 01:00:00 PM  11/08/2017 09:50:00 AM  6 days 20:50:00
169400  11/01/2017 01:00:00 PM  11/02/2017 08:38:00 AM  0 days 19:38:00
169399  11/01/2017 01:00:00 PM  11/03/2017 02:58:00 PM  2 days 01:58:00
169398  11/01/2017 01:00:00 PM  11/02/2017 10:31:00 AM  0 days 21:31:00
169397  11/01/2017 01:00:00 PM  11/09/2017 10:03:00 AM  7 days 21:03:00
...                        ...                     ...              ...
86556   11/30/2017 12:59:00 PM  12/01/2017 11:59:00 AM  0 days 23:00:00
86559   11/30/2017 12:59:00 PM  12/06/2017 08:03:00 AM  5 days 19:04:00
86558   11/30/2017 12:59:00 PM  12/05/2017 02:55:00 PM  5 days 01:56:00
86557   11/30/2017 12:59:00 PM  12/13/2017 03:12:00 PM 13 days 02:13:00
86555   11/30/2017 12:59:00 PM  12/04/2017 01:12:00 PM  4 days 00:13:00

[86477 rows x 3 columns]

Average Elapsed Time in November : 5.0 days, 1.0 hour, 4.0 minutes, 43.0 seconds