In [176]:
import numpy as np
import pandas as pd
from datetime import datetime 
from datetime import timedelta
import csv 
import matplotlib.pyplot as plt
from datetime import date
from datetime import time
import calendar
import locale
import seaborn as sns

In [177]:
def convertTimeStamp(string):
    """Converts a string to a datetime object.
    """
    time = datetime.strptime(string,'%m/%d/%Y %I:%M:%S %p') #Accepts time string, converts it to datetime object.
    return time

In [178]:
#convert seconds to weeks, days, hours, minutes, seconds

intervals = (
    ('weeks', 604800),  # 60 * 60 * 24 * 7
    ('days', 86400),    # 60 * 60 * 24
    ('hours', 3600),    # 60 * 60
    ('minutes', 60),
    ('seconds', 1),
    )

def display_time(seconds, granularity=2):
    result = []

    for name, count in intervals:
        value = seconds // count
        if value:
            seconds -= value * count
            if value == 1:
                name = name.rstrip('s')
            result.append("{} {}".format(value, name))
    return ', '.join(result[:granularity])

In [179]:
def elapsedInMonths(filepath):
    """councilTime accepts a csv file and returns a dataframe which displays the average elapsed time between created date 
        and update date for service requests in each distinct council district."""
    
    dataframe = pd.read_csv(filepath)
    
    
    #filter dateset to CreatedDate and UpdatedDate columns
    created_df = dataframe['CreatedDate'].dropna().apply(convertTimeStamp, 0) #apply convertTimeStamp to CreatedDate
    updated_df = dataframe['UpdatedDate'].dropna().apply(convertTimeStamp, 0) #apply convertTimeStamp to UpdatedDate
    
    
    #create elapsed time and elapsed seconds columns and insert into dataframe
    elapsed_df = updated_df - created_df #calculate the difference in the values in CreatedDate and UpdatedDate
    dataframe.insert(3, "ElapsedTime", elapsed_df) #insert column ElapsedTime with dataframe elapsed_df into dataframe dataframe
    elapsed_seconds = dataframe['ElapsedTime'].dt.total_seconds() #convert ElapsedTime values to seconds
    dataframe.insert(4, 'ElapsedTime in Seconds', elapsed_seconds)
    
    
    #convert CreatedDate and UpdatedDate to datetime objects
    created_df = pd.to_datetime(dataframe['CreatedDate'], format='%m/%d/%Y %I:%M:%S %p')
    updated_df = pd.to_datetime(dataframe['UpdatedDate'], format='%m/%d/%Y %I:%M:%S %p')
    
    
    df4 = dataframe[['CreatedDate', 'UpdatedDate', 'ElapsedTime', 'ElapsedTime in Seconds']] #create a dataframe df4 with dates and elapsed time columns from dataframe
    df4 = df4.sort_values(by = 'CreatedDate')
        
    
    #create a dataframe of the months of CreatedDate rows
    for row in range(0, len(created_df)-1):
        created_df[row] = created_df[row].month
        
    
    #create dataframes for each unique month with ElapsedTime column
    monthsList = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
    for num in range(0,11):
        month = monthsList[num]
        print('Elapsed Times in', month)
        
        #group CreatedDate by month
        is_month =  created_df==num+1
        df4_month = df4[is_month]
        
        #print columns CreatedDate, UpdatedDate, ElapsedTime, ElapsedTime in Seconds
        month_time = df4_month[['CreatedDate', 'UpdatedDate', 'ElapsedTime']]
        print(month_time)

        #find average elapsed time for each month
        elapsed_avg = df4_month['ElapsedTime in Seconds'].mean()
        elapsed_avg = display_time(elapsed_avg, 5)

        print('\nAverage Elapsed Time in', monthsList[num],':', elapsed_avg)
        print('\n\n')

In [180]:
elapsedInMonths(r"C:\Users\hanaa\Downloads\MyLA311_Service_Request_Data_2019.csv")

Elapsed Times in January
                  CreatedDate             UpdatedDate      ElapsedTime
410    01/01/2019 01:01:00 PM  01/02/2019 12:36:00 PM  0 days 23:35:00
409    01/01/2019 01:01:00 PM  04/11/2019 09:19:00 AM 99 days 20:18:00
408    01/01/2019 01:01:00 PM  04/11/2019 09:30:00 AM 99 days 20:29:00
407    01/01/2019 01:01:00 PM  03/19/2019 02:25:00 PM 77 days 01:24:00
413    01/01/2019 01:02:00 PM  01/03/2019 07:38:00 AM  1 days 18:36:00
...                       ...                     ...              ...
99574  01/31/2019 12:58:00 PM  02/04/2019 08:42:00 AM  3 days 19:44:00
99575  01/31/2019 12:58:00 PM  02/01/2019 03:14:00 PM  1 days 02:16:00
98267  01/31/2019 12:59:00 AM  03/12/2019 02:40:00 PM 40 days 13:41:00
98268  01/31/2019 12:59:00 AM  05/02/2019 04:35:00 PM 91 days 15:36:00
99577  01/31/2019 12:59:00 PM  02/03/2019 10:50:00 AM  2 days 21:51:00

[101120 rows x 3 columns]

Average Elapsed Time in January : 6.0 days, 11.0 hours, 14.0 minutes, 57.0 seconds



Elapsed Times in February
                   CreatedDate             UpdatedDate     ElapsedTime
102401  02/01/2019 01:00:00 PM  02/07/2019 02:26:00 PM 6 days 01:26:00
102402  02/01/2019 01:00:00 PM  02/04/2019 11:27:00 AM 2 days 22:27:00
102400  02/01/2019 01:00:00 PM  02/07/2019 09:47:00 AM 5 days 20:47:00
102399  02/01/2019 01:00:00 PM  02/07/2019 09:15:00 AM 5 days 20:15:00
102403  02/01/2019 01:01:00 PM  02/06/2019 10:47:00 AM 4 days 21:46:00
...                        ...                     ...             ...
178861  02/28/2019 12:57:00 PM  03/05/2019 12:30:00 PM 4 days 23:33:00
178862  02/28/2019 12:57:00 PM  03/06/2019 01:33:00 PM 6 days 00:36:00
178863  02/28/2019 12:59:00 PM  03/01/2019 11:20:00 AM 0 days 22:21:00
178865  02/28/2019 12:59:00 PM  03/01/2019 10:00:00 AM 0 days 21:01:00
178864  02/28/2019 12:59:00 PM  03/04/2019 09:10:00 AM 3 days 20:11:00

[79554 rows x 3 columns]

C:\Users\hanaa\Anaconda3\lib\site-packages\ipykernel_launcher.py:42: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

Average Elapsed Time in February : 6.0 days, 16.0 hours, 12.0 minutes, 36.0 seconds



Elapsed Times in March
                   CreatedDate             UpdatedDate      ElapsedTime
181857  03/01/2019 01:00:00 PM  03/07/2019 06:43:00 AM  5 days 17:43:00
181859  03/01/2019 01:00:00 PM  03/04/2019 01:35:00 PM  3 days 00:35:00
181858  03/01/2019 01:00:00 PM  03/05/2019 01:30:00 PM  4 days 00:30:00
181855  03/01/2019 01:00:00 PM  03/08/2019 02:10:00 PM  7 days 01:10:00
181856  03/01/2019 01:00:00 PM  03/04/2019 12:08:00 PM  2 days 23:08:00
...                        ...                     ...              ...
273555  03/31/2019 12:59:00 PM  04/04/2019 02:43:00 PM  4 days 01:44:00
273557  03/31/2019 12:59:00 PM  04/03/2019 11:00:00 AM  2 days 22:01:00
273556  03/31/2019 12:59:00 PM  04/05/2019 06:55:00 AM  4 days 17:56:00
273554  03/31/2019 12:59:00 PM  04/10/2019 07:49:00 PM 10 days 06:50:00
273558  03/31/2019 12:59:00 PM  04/03/2019 03:06:00 PM  3 days 02:07:00

[94214 rows x 3 columns]

Average Elapsed Time in March : 6.0 days, 11.0 hours, 2.0 minutes, 32.0 seconds



Elapsed Times in April
                   CreatedDate             UpdatedDate      ElapsedTime
274903  04/01/2019 01:00:00 AM  04/03/2019 06:50:00 AM  2 days 05:50:00
277358  04/01/2019 01:00:00 PM  04/04/2019 03:14:00 PM  3 days 02:14:00
277359  04/01/2019 01:00:00 PM  04/08/2019 03:29:00 PM  7 days 02:29:00
277356  04/01/2019 01:00:00 PM  04/09/2019 05:49:00 PM  8 days 04:49:00
277357  04/01/2019 01:00:00 PM  04/03/2019 07:35:00 AM  1 days 18:35:00
...                        ...                     ...              ...
389822  04/30/2019 12:59:00 PM  06/24/2019 11:44:00 AM 54 days 22:45:00
389823  04/30/2019 12:59:00 PM  05/01/2019 12:45:00 PM  0 days 23:46:00
389824  04/30/2019 12:59:00 PM  05/03/2019 02:19:00 PM  3 days 01:20:00
389825  04/30/2019 12:59:00 PM  05/07/2019 09:34:00 AM  6 days 20:35:00
389827  04/30/2019 12:59:00 PM  05/06/2019 01:32:00 PM  6 days 00:33:00

[117480 rows x 3 columns]

Average Elapsed Time in April : 5.0 days, 16.0 hours, 26.0 minutes, 10.0 seconds



Elapsed Times in May
                   CreatedDate             UpdatedDate      ElapsedTime
392399  05/01/2019 01:00:00 AM  05/06/2019 10:55:00 AM  5 days 09:55:00
394714  05/01/2019 01:00:00 PM  05/13/2019 09:48:00 AM 11 days 20:48:00
394715  05/01/2019 01:00:00 PM  05/03/2019 04:53:00 PM  2 days 03:53:00
394716  05/01/2019 01:00:00 PM  05/06/2019 11:57:00 AM  4 days 22:57:00
394717  05/01/2019 01:00:00 PM  05/06/2019 01:08:00 PM  5 days 00:08:00
...                        ...                     ...              ...
495490  05/31/2019 12:59:00 PM  05/31/2019 05:10:00 PM  0 days 04:11:00
495491  05/31/2019 12:59:00 PM  06/03/2019 07:39:00 PM  3 days 06:40:00
495492  05/31/2019 12:59:00 PM  06/04/2019 07:57:00 AM  3 days 18:58:00
495493  05/31/2019 12:59:00 PM  06/04/2019 05:45:00 AM  3 days 16:46:00
495495  05/31/2019 12:59:00 PM  06/06/2019 06:49:00 PM  6 days 05:50:00

[105155 rows x 3 columns]

Average Elapsed Time in May : 6.0 days, 9.0 hours, 34.0 minutes, 40.0 seconds



Elapsed Times in June
                   CreatedDate             UpdatedDate     ElapsedTime
498487  06/01/2019 01:00:00 PM  06/01/2019 01:42:00 PM 0 days 00:42:00
498486  06/01/2019 01:00:00 PM  06/02/2019 03:42:00 PM 1 days 02:42:00
498488  06/01/2019 01:01:00 PM  06/06/2019 04:02:00 PM 5 days 03:01:00
498489  06/01/2019 01:01:00 PM  06/07/2019 02:18:00 PM 6 days 01:17:00
498490  06/01/2019 01:02:00 PM  06/01/2019 04:19:00 PM 0 days 03:17:00
...                        ...                     ...             ...
608332  06/30/2019 12:59:00 AM  06/30/2019 01:00:00 AM 0 days 00:01:00
609367  06/30/2019 12:59:00 PM  07/03/2019 06:46:00 PM 3 days 05:47:00
609364  06/30/2019 12:59:00 PM  06/30/2019 01:00:00 PM 0 days 00:01:00
609365  06/30/2019 12:59:00 PM  07/01/2019 10:06:00 AM 0 days 21:07:00
609366  06/30/2019 12:59:00 PM  07/03/2019 05:23:00 PM 3 days 04:24:00

[113393 rows x 3 columns]

Average Elapsed Time in June : 6.0 days, 5.0 hours, 50.0 minutes, 32.0 seconds



Elapsed Times in July
                   CreatedDate             UpdatedDate     ElapsedTime
610929  07/01/2019 01:00:00 AM  07/02/2019 11:59:00 PM 1 days 22:59:00
613624  07/01/2019 01:00:00 PM  07/06/2019 09:18:00 AM 4 days 20:18:00
613625  07/01/2019 01:00:00 PM  07/03/2019 12:04:00 AM 1 days 11:04:00
613626  07/01/2019 01:00:00 PM  07/03/2019 03:50:00 PM 2 days 02:50:00
613627  07/01/2019 01:00:00 PM  07/02/2019 05:25:00 PM 1 days 04:25:00
...                        ...                     ...             ...
734872  07/31/2019 12:59:00 PM  08/06/2019 07:26:00 AM 5 days 18:27:00
734873  07/31/2019 12:59:00 PM  08/08/2019 11:16:00 AM 7 days 22:17:00
734874  07/31/2019 12:59:00 PM  08/06/2019 02:07:00 PM 6 days 01:08:00
734875  07/31/2019 12:59:00 PM  08/06/2019 04:35:00 PM 6 days 03:36:00
734877  07/31/2019 12:59:00 PM  08/02/2019 05:58:00 PM 2 days 04:59:00

[126917 rows x 3 columns]

Average Elapsed Time in July : 5.0 days, 18.0 hours, 57.0 minutes, 6.0 seconds



Elapsed Times in August
                   CreatedDate             UpdatedDate       ElapsedTime
737854  08/01/2019 01:00:00 AM  08/20/2019 01:31:00 PM  19 days 12:31:00
740550  08/01/2019 01:00:00 PM  08/06/2019 09:29:00 AM   4 days 20:29:00
740551  08/01/2019 01:00:00 PM  09/26/2019 12:10:00 PM  55 days 23:10:00
740552  08/01/2019 01:00:00 PM  08/02/2019 07:32:00 AM   0 days 18:32:00
740553  08/01/2019 01:00:00 PM  08/02/2019 04:25:00 PM   1 days 03:25:00
...                        ...                     ...               ...
858430  08/31/2019 12:57:00 PM  01/22/2020 01:25:00 PM 144 days 00:28:00
858433  08/31/2019 12:58:00 PM  09/10/2019 04:50:00 PM  10 days 03:52:00
858434  08/31/2019 12:58:00 PM  09/12/2019 06:12:00 PM  12 days 05:14:00
858435  08/31/2019 12:58:00 PM  09/03/2019 08:54:00 AM   2 days 19:56:00
858436  08/31/2019 12:59:00 PM  09/03/2019 01:13:00 PM   3 days 00:14:00

[121428 rows x 3 columns]

Average Elapsed Time in August : 5.0 days, 16.0 hours, 37.0 minutes, 59.0 seconds



Elapsed Times in September
                   CreatedDate             UpdatedDate     ElapsedTime
859848  09/01/2019 01:00:00 PM  09/03/2019 03:50:00 PM 2 days 02:50:00
859849  09/01/2019 01:00:00 PM  09/03/2019 02:49:00 PM 2 days 01:49:00
859850  09/01/2019 01:01:00 PM  09/03/2019 02:41:00 PM 2 days 01:40:00
859851  09/01/2019 01:02:00 PM  09/03/2019 02:48:00 PM 2 days 01:46:00
859852  09/01/2019 01:03:00 PM  09/07/2019 06:28:00 PM 6 days 05:25:00
...                        ...                     ...             ...
971307  09/30/2019 12:59:00 AM  09/30/2019 01:00:00 AM 0 days 00:01:00
973582  09/30/2019 12:59:00 PM  10/01/2019 08:04:00 AM 0 days 19:05:00
973580  09/30/2019 12:59:00 PM  10/04/2019 04:23:00 PM 4 days 03:24:00
973581  09/30/2019 12:59:00 PM  10/02/2019 11:39:00 AM 1 days 22:40:00
973583  09/30/2019 12:59:00 PM  10/07/2019 04:09:00 PM 7 days 03:10:00

[117563 rows x 3 columns]

Average Elapsed Time in September : 5.0 days, 16.0 hours, 28.0 minutes, 22.0 seconds



Elapsed Times in October
                    CreatedDate             UpdatedDate     ElapsedTime
979708   10/01/2019 01:00:00 PM  10/02/2019 05:58:00 PM 1 days 04:58:00
979709   10/01/2019 01:00:00 PM  10/03/2019 02:13:00 PM 2 days 01:13:00
979706   10/01/2019 01:00:00 PM  10/02/2019 06:32:00 PM 1 days 05:32:00
979707   10/01/2019 01:00:00 PM  10/02/2019 12:06:00 PM 0 days 23:06:00
979710   10/01/2019 01:01:00 PM  10/02/2019 02:19:00 PM 1 days 01:18:00
...                         ...                     ...             ...
1093939  10/31/2019 12:58:00 PM  11/01/2019 09:29:00 AM 0 days 20:31:00
1093943  10/31/2019 12:59:00 PM  11/01/2019 03:48:00 PM 1 days 02:49:00
1093942  10/31/2019 12:59:00 PM  11/06/2019 07:31:00 AM 5 days 18:32:00
1093941  10/31/2019 12:59:00 PM  11/01/2019 02:23:00 PM 1 days 01:24:00
1093940  10/31/2019 12:59:00 PM  11/01/2019 01:52:00 PM 1 days 00:53:00

[118843 rows x 3 columns]

Average Elapsed Time in October : 6.0 days, 4.0 hours, 21.0 minutes, 14.0 seconds



Elapsed Times in November
                    CreatedDate             UpdatedDate     ElapsedTime
1097248  11/01/2019 01:00:00 PM  11/05/2019 08:34:00 AM 3 days 19:34:00
1097249  11/01/2019 01:00:00 PM  11/11/2019 11:21:00 AM 9 days 22:21:00
1095680  11/01/2019 01:01:00 AM  11/01/2019 01:04:00 PM 0 days 12:03:00
1097250  11/01/2019 01:01:00 PM  11/04/2019 07:30:00 AM 2 days 18:29:00
1097251  11/01/2019 01:01:00 PM  11/01/2019 01:05:00 PM 0 days 00:04:00
...                         ...                     ...             ...
1200338  11/30/2019 12:58:00 PM  12/02/2019 11:19:00 AM 1 days 22:21:00
1200341  11/30/2019 12:59:00 PM  12/04/2019 10:47:00 AM 3 days 21:48:00
1200339  11/30/2019 12:59:00 PM  12/04/2019 08:02:00 AM 3 days 19:03:00
1200340  11/30/2019 12:59:00 PM  12/04/2019 11:47:00 AM 3 days 22:48:00
1200342  11/30/2019 12:59:00 PM  12/03/2019 07:39:00 AM 2 days 18:40:00

[105758 rows x 3 columns]

Average Elapsed Time in November : 5.0 days, 5.0 hours, 44.0 minutes, 44.0 seconds