In [27]:
import numpy as np
import pandas as pd
from datetime import datetime 
import csv 
import matplotlib.pyplot as plt
from datetime import date
from datetime import time

In [28]:
def convertTimeStamp(string):
    """Converts a string to a datetime object.
    """
    time = datetime.strptime(string,'%m/%d/%Y %I:%M:%S %p') #Accepts time string, converts it to datetime object.
    return time
    
def elapsedTime(filepath):
    dataframe = pd.read_csv(filepath)
    
    #filter dateset to CreatedDate and UpdatedDate columns
    created_df = dataframe['CreatedDate'].dropna().apply(convertTimeStamp, 0) #apply convertTimeStamp to CreatedDate
    updated_df = dataframe['UpdatedDate'].dropna().apply(convertTimeStamp, 0) #apply convertTimeStamp to UpdatedDate
    
    #create elapsedTime column
    elapsed_df = updated_df - created_df #calculate the difference in the values in CreatedDate and UpdatedDate
    dataframe.insert(3, "ElapsedTime", elapsed_df) #create column ElapsedTime with dataframe elapsed_df into dataframe dataframe
    df1 = dataframe[['CreatedDate', 'UpdatedDate', 'ElapsedTime']]

    
    return df1

In [29]:
elapsedTime(r"C:\Users\hanaa\Downloads\MyLA311_Service_Request_Data_2019.csv")

                    CreatedDate             UpdatedDate      ElapsedTime
0        01/01/2019 12:02:00 AM  01/04/2019 11:03:00 AM  3 days 11:01:00
1        01/01/2019 12:05:00 AM  01/01/2019 12:09:00 AM  0 days 00:04:00
2        01/01/2019 12:10:00 AM  01/03/2019 12:27:00 AM  2 days 00:17:00
3        01/01/2019 12:19:00 AM  01/07/2019 09:43:00 AM  6 days 09:24:00
4        01/01/2019 12:28:00 AM  01/03/2019 12:28:00 AM  2 days 00:00:00
...                         ...                     ...              ...
1308088  12/31/2019 11:26:00 PM  01/03/2020 04:09:00 PM  2 days 16:43:00
1308089  12/31/2019 11:26:00 PM  01/14/2020 07:52:00 AM 13 days 08:26:00
1308090  12/31/2019 11:30:00 PM  01/03/2020 11:36:00 AM  2 days 12:06:00
1308091  12/31/2019 11:54:00 PM  01/06/2020 08:45:00 PM  5 days 20:51:00
1308092  12/31/2019 11:58:00 PM  01/15/2020 10:51:00 AM 14 days 10:53:00

[1308093 rows x 3 columns]